const demodata = [
  {
    id: 1,
    title: 'Metal Shoes',
    description: 'Durable and stylish metal shoes, perfect for any occasion.',
    price: "₹89400",
    username: 'Yancy Tear',
    country: 'Brazil',
    time: '12:45',
    date: 'Auguest 29, 2024',
    imageUrl: 'https://img.daisyui.com/images/profile/demo/5@94.webp',
  },
  {
    id: 2,
    title: 'Leather Jacket',
    description: 'High-quality leather jacket with a sleek finish.',
    price: "₹14500",
    username: 'John Doe',
    country: 'USA',
    time: '14:30',
    date: 'Auguest 29, 2024',
    imageUrl: 'https://img.daisyui.com/images/profile/demo/5@94.webp',
  },
  {
    id: 3,
    title: 'Smart Watch',
    description: 'Stay connected and track your fitness with this smart watch.',
    price: "₹22000",
    username: 'Anna Smith',
    country: 'UK',
    time: '09:00',
    date: 'Auguest 29, 2024',
    imageUrl: 'https://img.daisyui.com/images/profile/demo/5@94.webp',
  },
  {
    id: 4,
    title: 'Wireless Earbuds',
    description: 'Enjoy high-quality sound without the wires.',
    price: "₹4500",
    username: 'Maria Garcia',
    country: 'Spain',
    time: '17:15',
    date: 'Auguest 29, 2024',
    imageUrl: 'https://img.daisyui.com/images/profile/demo/5@94.webp',
  },
  {
    id: 5,
    title: 'Gaming Laptop',
    description: 'High-performance laptop for gaming and productivity.',
    price: "₹12500",
    username: 'Michael Lee',
    country: 'South Korea',
    time: '21:00',
    date: 'Auguest 29, 2024',
    imageUrl: 'https://img.daisyui.com/images/profile/demo/5@94.webp',
  },
];

export default demodata;
